ordinal_map = {
    # 1-20
    "erste": 1, "erster": 1, "erstes": 1, "ersten": 1, "erst": 1,
    "zweite": 2, "zweiter": 2, "zweites": 2, "zweiten": 2, "zweit": 2,
    "dritte": 3, "dritter": 3, "drittes": 3, "dritten": 3, "dritt": 3,
    "vierte": 4, "vierter": 4, "viertes": 4, "vierten": 4, "viert": 4,
    "fünfte": 5, "fünfter": 5, "fünftes": 5, "fünften": 5, "fünft": 5,
    "sechste": 6, "sechster": 6, "sechstes": 6, "sechsten": 6, "sechst": 6,
    "siebte": 7, "siebter": 7, "siebtes": 7, "siebten": 7, "siebt": 7,
    "achte": 8, "achter": 8, "achtes": 8, "achten": 8, "acht": 8,
    "neunte": 9, "neunter": 9, "neuntes": 9, "neunten": 9, "neunt": 9,
    "zehnte": 10, "zehnter": 10, "zehntes": 10, "zehnten": 10, "zehnt": 10,
    "elfte": 11, "elfter": 11, "elftes": 11, "elften": 11, "elft": 11,
    "zwölfte": 12, "zwölfter": 12, "zwölftes": 12, "zwölften": 12, "zwölft": 12,
    "dreizehnte": 13, "dreizehnter": 13, "dreizehntes": 13, "dreizehnten": 13, "dreizehnt": 13,
    "vierzehnte": 14, "vierzehnter": 14, "vierzehntes": 14, "vierzehnten": 14, "vierzehnt": 14,
    "fünfzehnte": 15, "fünfzehnter": 15, "fünfzehntes": 15, "fünfzehnten": 15, "fünfzehnt": 15,
    "sechzehnte": 16, "sechzehnter": 16, "sechzehntes": 16, "sechzehnten": 16, "sechzehnt": 16,
    "siebzehnte": 17, "siebzehnter": 17, "siebzehntes": 17, "siebzehnten": 17, "siebzehnt": 17,
    "achtzehnte": 18, "achtzehnter": 18, "achtzehntes": 18, "achtzehnten": 18, "achtzehnt": 18,
    "neunzehnte": 19, "neunzehnter": 19, "neunzehntes": 19, "neunzehnten": 19, "neunzehnt": 19,
    "zwanzigste": 20, "zwanzigster": 20, "zwanzigstes": 20, "zwanzigsten": 20, "zwanzigst": 20,

    # 21-30
    "einundzwanzigste": 21, "einundzwanzigster": 21, "einundzwanzigstes": 21, "einundzwanzigsten": 21,
    "zweiundzwanzigste": 22, "zweiundzwanzigster": 22, "zweiundzwanzigstes": 22, "zweiundzwanzigsten": 22,
    "dreiundzwanzigste": 23, "dreiundzwanzigster": 23, "dreiundzwanzigstes": 23, "dreiundzwanzigsten": 23,
    "vierundzwanzigste": 24, "vierundzwanzigster": 24, "vierundzwanzigstes": 24, "vierundzwanzigsten": 24,
    "fünfundzwanzigste": 25, "fünfundzwanzigster": 25, "fünfundzwanzigstes": 25, "fünfundzwanzigsten": 25,
    "sechsundzwanzigste": 26, "sechsundzwanzigster": 26, "sechsundzwanzigstes": 26, "sechsundzwanzigsten": 26,
    "siebenundzwanzigste": 27, "siebenundzwanzigster": 27, "siebenundzwanzigstes": 27, "siebenundzwanzigsten": 27,
    "achtundzwanzigste": 28, "achtundzwanzigster": 28, "achtundzwanzigstes": 28, "achtundzwanzigsten": 28,
    "neunundzwanzigste": 29, "neunundzwanzigster": 29, "neunundzwanzigstes": 29, "neunundzwanzigsten": 29,
    "dreißigste": 30, "dreißigster": 30, "dreißigstes": 30, "dreißigsten": 30,

    # 31-40
    "einunddreißigste": 31, "einunddreißigster": 31, "einunddreißigstes": 31, "einunddreißigsten": 31,
    "zweiunddreißigste": 32, "zweiunddreißigster": 32, "zweiunddreißigstes": 32, "zweiunddreißigsten": 32,
    "dreiunddreißigste": 33, "dreiunddreißigster": 33, "dreiunddreißigstes": 33, "dreiunddreißigsten": 33,
    "vierunddreißigste": 34, "vierunddreißigster": 34, "vierunddreißigstes": 34, "vierunddreißigsten": 34,
    "fünfunddreißigste": 35, "fünfunddreißigster": 35, "fünfunddreißigstes": 35, "fünfunddreißigsten": 35,
    "sechsunddreißigste": 36, "sechsunddreißigster": 36, "sechsunddreißigstes": 36, "sechsunddreißigsten": 36,
    "siebenunddreißigste": 37, "siebenunddreißigster": 37, "siebenunddreißigstes": 37, "siebenunddreißigsten": 37,
    "achtunddreißigste": 38, "achtunddreißigster": 38, "achtunddreißigstes": 38, "achtunddreißigsten": 38,
    "neununddreißigste": 39, "neununddreißigster": 39, "neununddreißigstes": 39, "neununddreißigsten": 39,
    "vierzigste": 40, "vierzigster": 40, "vierzigstes": 40, "vierzigsten": 40,

    # 41-50
    "einundvierzigste": 41, "einundvierzigster": 41, "einundvierzigstes": 41, "einundvierzigsten": 41,
    "zweiundvierzigste": 42, "zweiundvierzigster": 42, "zweiundvierzigstes": 42, "zweiundvierzigsten": 42,
    "dreiundvierzigste": 43, "dreiundvierzigster": 43, "dreiundvierzigstes": 43, "dreiundvierzigsten": 43,
    "vierundvierzigste": 44, "vierundvierzigster": 44, "vierundvierzigstes": 44, "vierundvierzigsten": 44,
    "fünfundvierzigste": 45, "fünfundvierzigster": 45, "fünfundvierzigstes": 45, "fünfundvierzigsten": 45,
    "sechsundvierzigste": 46, "sechsundvierzigster": 46, "sechsundvierzigstes": 46, "sechsundvierzigsten": 46,
    "siebenundvierzigste": 47, "siebenundvierzigster": 47, "siebenundvierzigstes": 47, "siebenundvierzigsten": 47,
    "achtundvierzigste": 48, "achtundvierzigster": 48, "achtundvierzigstes": 48, "achtundvierzigsten": 48,
    "neunundvierzigste": 49, "neunundvierzigster": 49, "neunundvierzigstes": 49, "neunundvierzigsten": 49,
    "fünfzigste": 50, "fünfzigster": 50, "fünfzigstes": 50, "fünfzigsten": 50,

    # 51-60
    "einundfünfzigste": 51, "einundfünfzigster": 51, "einundfünfzigstes": 51, "einundfünfzigsten": 51,
    "zweiundfünfzigste": 52, "zweiundfünfzigster": 52, "zweiundfünfzigstes": 52, "zweiundfünfzigsten": 52,
    "dreiundfünfzigste": 53, "dreiundfünfzigster": 53, "dreiundfünfzigstes": 53, "dreiundfünfzigsten": 53,
    "vierundfünfzigste": 54, "vierundfünfzigster": 54, "vierundfünfzigstes": 54, "vierundfünfzigsten": 54,
    "fünfundfünfzigste": 55, "fünfundfünfzigster": 55, "fünfundfünfzigstes": 55, "fünfundfünfzigsten": 55,
    "sechsundfünfzigste": 56, "sechsundfünfzigster": 56, "sechsundfünfzigstes": 56, "sechsundfünfzigsten": 56,
    "siebenundfünfzigste": 57, "siebenundfünfzigster": 57, "siebenundfünfzigstes": 57, "siebenundfünfzigsten": 57,
    "achtundfünfzigste": 58, "achtundfünfzigster": 58, "achtundfünfzigstes": 58, "achtundfünfzigsten": 58,
    "neunundfünfzigste": 59, "neunundfünfzigster": 59, "neunundfünfzigstes": 59, "neunundfünfzigsten": 59,
    "sechzigste": 60, "sechzigster": 60, "sechzigstes": 60, "sechzigsten": 60,

    # 61-70
    "einundsechzigste": 61, "einundsechzigster": 61, "einundsechzigstes": 61, "einundsechzigsten": 61,
    "zweiundsechzigste": 62, "zweiundsechzigster": 62, "zweiundsechzigstes": 62, "zweiundsechzigsten": 62,
    "dreiundsechzigste": 63, "dreiundsechzigster": 63, "dreiundsechzigstes": 63, "dreiundsechzigsten": 63,
    "vierundsechzigste": 64, "vierundsechzigster": 64, "vierundsechzigstes": 64, "vierundsechzigsten": 64,
    "fünfundsechzigste": 65, "fünfundsechzigster": 65, "fünfundsechzigstes": 65, "fünfundsechzigsten": 65,
    "sechsundsechzigste": 66, "sechsundsechzigster": 66, "sechsundsechzigstes": 66, "sechsundsechzigsten": 66,
    "siebenundsechzigste": 67, "siebenundsechzigster": 67, "siebenundsechzigstes": 67, "siebenundsechzigsten": 67,
    "achtundsechzigste": 68, "achtundsechzigster": 68, "achtundsechzigstes": 68, "achtundsechzigsten": 68,
    "neunundsechzigste": 69, "neunundsechzigster": 69, "neunundsechzigstes": 69, "neunundsechzigsten": 69,
    "siebzigste": 70, "siebzigster": 70, "siebzigstes": 70, "siebzigsten": 70,

    # 71-80
    "einundsiebzigste": 71, "einundsiebzigster": 71, "einundsiebzigstes": 71, "einundsiebzigsten": 71,
    "zweiundsiebzigste": 72, "zweiundsiebzigster": 72, "zweiundsiebzigstes": 72, "zweiundsiebzigsten": 72,
    "dreiundsiebzigste": 73, "dreiundsiebzigster": 73, "dreiundsiebzigstes": 73, "dreiundsiebzigsten": 73,
    "vierundsiebzigste": 74, "vierundsiebzigster": 74, "vierundsiebzigstes": 74, "vierundsiebzigsten": 74,
    "fünfundsiebzigste": 75, "fünfundsiebzigster": 75, "fünfundsiebzigstes": 75, "fünfundsiebzigsten": 75,
    "sechsundsiebzigste": 76, "sechsundsiebzigster": 76, "sechsundsiebzigstes": 76, "sechsundsiebzigsten": 76,
    "siebenundsiebzigste": 77, "siebenundsiebzigster": 77, "siebenundsiebzigstes": 77, "siebenundsiebzigsten": 77,
    "achtundsiebzigste": 78, "achtundsiebzigster": 78, "achtundsiebzigstes": 78, "achtundsiebzigsten": 78,
    "neunundsiebzigste": 79, "neunundsiebzigster": 79, "neunundsiebzigstes": 79, "neunundsiebzigsten": 79,
    "achtzigste": 80, "achtzigster": 80, "achtzigstes": 80, "achtzigsten": 80,

    # 81-90
    "einundachtzigste": 81, "einundachtzigster": 81, "einundachtzigstes": 81, "einundachtzigsten": 81,
    "zweiundachtzigste": 82, "zweiundachtzigster": 82, "zweiundachtzigstes": 82, "zweiundachtzigsten": 82,
    "dreiundachtzigste": 83, "dreiundachtzigster": 83, "dreiundachtzigstes": 83, "dreiundachtzigsten": 83,
    "vierundachtzigste": 84, "vierundachtzigster": 84, "vierundachtzigstes": 84, "vierundachtzigsten": 84,
    "fünfundachtzigste": 85, "fünfundachtzigster": 85, "fünfundachtzigstes": 85, "fünfundachtzigsten": 85,
    "sechsundachtzigste": 86, "sechsundachtzigster": 86, "sechsundachtzigstes": 86, "sechsundachtzigsten": 86,
    "siebenundachtzigste": 87, "siebenundachtzigster": 87, "siebenundachtzigstes": 87, "siebenundachtzigsten": 87,
    "achtundachtzigste": 88, "achtundachtzigster": 88, "achtundachtzigstes": 88, "achtundachtzigsten": 88,
    "neunundachtzigste": 89, "neunundachtzigster": 89, "neunundachtzigstes": 89, "neunundachtzigsten": 89,
    "neunzigste": 90, "neunzigster": 90, "neunzigstes": 90, "neunzigsten": 90,

    # 91-100
    "einundneunzigste": 91, "einundneunzigster": 91, "einundneunzigstes": 91, "einundneunzigsten": 91,
    "zweiundneunzigste": 92, "zweiundneunzigster": 92, "zweiundneunzigstes": 92, "zweiundneunzigsten": 92,
    "dreiundneunzigste": 93, "dreiundneunzigster": 93, "dreiundneunzigstes": 93, "dreiundneunzigsten": 93,
    "vierundneunzigste": 94, "vierundneunzigster": 94, "vierundneunzigstes": 94, "vierundneunzigsten": 94,
    "fünfundneunzigste": 95, "fünfundneunzigster": 95, "fünfundneunzigstes": 95, "fünfundneunzigsten": 95,
    "sechsundneunzigste": 96, "sechsundneunzigster": 96, "sechsundneunzigstes": 96, "sechsundneunzigsten": 96,
    "siebenundneunzigste": 97, "siebenundneunzigster": 97, "siebenundneunzigstes": 97, "siebenundneunzigsten": 97,
    "achtundneunzigste": 98, "achtundneunzigster": 98, "achtundneunzigstes": 98, "achtundneunzigsten": 98,
    "neunundneunzigste": 99, "neunundneunzigster": 99, "neunundneunzigstes": 99, "neunundneunzigsten": 99,
    "hundertste": 100, "hundertster": 100, "hundertstes": 100, "hundertsten": 100,
}
